dglでは全て有向グラフとして扱う．

In [1]:
import dgl
import torch
# https://docs.dgl.ai/en/0.6.x/guide/graph-graphs-nodes-edges.html
# u: 始点，v: 終点
u, v = torch.tensor([0,0,0,1]), torch.tensor([1,2,3,3])
g = dgl.graph((u, v))
print(g)

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


In [2]:
print(g.nodes())

tensor([0, 1, 2, 3])


In [3]:
print(g.edges())

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))


In [4]:
# edge idも後ろに加わる
print(g.edges(form='all'))

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))
